"""empty message

Revision ID: 67da4c15be7e
Revises: e2d39bee74ec
Create Date: 2025-10-26 01:13:10.976302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67da4c15be7e'
down_revision: Union[str, Sequence[str], None] = 'e2d39bee74ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('order_user_id_fkey'), 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'cart_item', ['cart_item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'order', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key(op.f('order_user_id_fkey'), 'order', 'cart_item', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
