"""empty message

Revision ID: 9a7723f09280
Revises: 435c7125ec2c
Create Date: 2025-10-26 00:53:54.355218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a7723f09280'
down_revision: Union[str, Sequence[str], None] = '435c7125ec2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cart', ['id'])
    op.create_unique_constraint(None, 'cart_item', ['id'])
    op.create_unique_constraint(None, 'order', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='unique')
    op.drop_constraint(None, 'cart_item', type_='unique')
    op.drop_constraint(None, 'cart', type_='unique')
    # ### end Alembic commands ###
